title: Machine Learning aplicada a segurança em Internet das Coisas detectando anomalias na comunicação e operação
description: Trabalho de Graduação em Engenharia de Computação na EPUSP. 
theme: jekyll-theme-cayman
